version: '3.8'

services:
  # 1. Auth Service
  auth-service:
    build: ./auth-service
    environment:
      - JWT_SECRET=super-secret-key
    networks:
      - jwt-net

  # 2. Task Service
  task-service:
    build: ./task-service
    environment:
      - JWT_SECRET=super-secret-key
    networks:
      - jwt-net

  # 3. User Service
  user-service:
    build: ./user-service
    environment:
      - JWT_SECRET=super-secret-key
    networks:
      - jwt-net

  # 4. API Gateway (Nginx)
  gateway:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service
      - task-service
      - user-service
    networks:
      - jwt-net

networks:
  jwt-net:
    driver: bridge
