server {
    listen 80;

    # Auth Service
    location /auth {
        proxy_pass http://auth-service:5001/auth;
    }

    # Task Service
    location /api/tasks {
        proxy_pass http://task-service:5002/api/tasks;
    }

    # User Service
    location /api/users {
        proxy_pass http://user-service:5003/api/users;
    }

    # Frontend (Optional for lab simulation)
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
